### ISSUE TITLE
Please add an option to add it directly to the editor window.

### ISSUE THREAD

**Issue by Chris2011** [Chris2011/nb-codeoutline#4]
This plugin is very nice, but when I want to use the editor window in fullscreen mode, the code outline window disappears, as expected, but when I see this feature in sublime, it is directly inside the editor window, not as a new window or so. It would be nice, if we can have an option to change this behaviour. So someone would like to have it as a separate window, and someone (like me) doesn't want it.
This would be very nice.

Regards

Chris

**Comment by markiewb** [comment]
It is possible. This is only the first version, which I hacked together in
a few hours. A TC was the easiest way

Best regards, markiewb

**Comment by markiewb** [comment]
Notes for the implementation
- https://blogs.oracle.com/geertjan/entry/org_netbeans_editor_sidebarfactory
- https://blogs.oracle.com/geertjan/entry/org_netbeans_editor_sidebarfactory_part

**Comment by markiewb** [comment]
@Chris2011: I guess you mean also the "show only editor" mode?!

**Comment by markiewb** [comment]
Since version 1.1.0 there is no window anymore. 

It is now integrated in every editor at the right side. 

This is more more useful, because
- you can use the outline in fullscreen/showonlyeditor mode too AND
- you can use the outline even there are multiple open editors at the same time (was not possible before)

**Comment by Chris2011** [comment]
You guess it right ;). Sounds cool, I will have a look, at the new version. thx dude.
